2023-Internetprogramming/team-03

- .gitignore
> Fix: gitignore 수정

- ott_posts/admin.py
- ott_posts/forms.py
- ott_posts/models.py
- ott_posts/templates/ott_posts/ott_detail.html
- ott_posts/templates/ott_posts/ott_form.html
- ott_posts/templates/ott_posts/ott_list.html
- ott_posts/urls.py
- ott_posts/views.py
- taxi_posts/forms.py
- taxi_posts/templates/taxi_posts/base.html
- taxi_posts/templates/taxi_posts/footer.html
- taxi_posts/templates/taxi_posts/ride_list.html
- www/urls.py
ott앱 forms.py 생성
어떤 변경 사항이 있나요?
> Feat: ott앱 forms.py 생성

- taxi_posts/templates/taxi_posts/navbar.html
nav바 수정 - 검색, 로그인 오른쪽으로 보냈습니다
Resolves: #4 
어떤 변경 사항이 있나요?
> Fix: nav바 수정

- ott_posts/templates/ott_posts/ott_detail.html
- ott_posts/templates/ott_posts/ott_form.html
- ott_posts/templates/ott_posts/ott_list.html
- ott_posts/urls.py
- ott_posts/views.py
- taxi_posts/static/taxi_posts/css/list.css
- taxi_posts/static/taxi_posts/css/plus.js
- taxi_posts/templates/taxi_posts/base.html
- taxi_posts/templates/taxi_posts/footer.html
- taxi_posts/templates/taxi_posts/navbar.html
- taxi_posts/templates/taxi_posts/ride_detail.html
- taxi_posts/templates/taxi_posts/ride_form.html
- taxi_posts/templates/taxi_posts/ride_list.html
- taxi_posts/urls.py
- taxi_posts/views.py
- www/settings.py
taxi_posts앱과 ott_posts앱에 페이지네이션 추가하고 CBV형식으로 변경
어떤 변경 사항이 있나요?
> Feat: 페이지네이션 추가, CBV형식으로 변경

- ott_posts/templates/ott_posts/ott_detail.html
- ott_posts/templates/ott_posts/ott_list.html
- ott_posts/urls.py
- ott_posts/views.py
- taxi_posts/models.py
- taxi_posts/static/taxi_posts/css/list.css
- taxi_posts/templates/taxi_posts/ride_detail.html
- taxi_posts/templates/taxi_posts/ride_list.html
- taxi_posts/urls.py
- taxi_posts/views.py
taxi_posts앱 ／ott_posts 앱 게시물 삭제 기능 추가, FBV형식으로 변경
어떤 변경 사항이 있나요?
> Feat: 게시물 삭제 기능 추가, FBV형식으로 변경

- ott_posts/templates/ott_posts/ott_detail.html
- ott_posts/templates/ott_posts/ott_list.html
- ott_posts/templates/ott_posts/ott_update.html
- ott_posts/urls.py
- ott_posts/views.py
- taxi_posts/templates/taxi_posts/ride_detail.html
- taxi_posts/templates/taxi_posts/ride_list.html
- taxi_posts/templates/taxi_posts/ride_update.html
- taxi_posts/urls.py
- taxi_posts/views.py
- www/settings.py
taxi/ott 게시물 수정 기능 추가
어떤 변경 사항이 있나요?
> Feat: taxi/ott게시물 수정 기능 추가

- contest/models.py
- contest/static/contest/css/contest.css
- contest/templates/contest/contest_detail.html
- contest/templates/contest/contest_list.html
- contest/urls.py
- contest/views.py
- ott_posts/templates/ott_posts/ott_list.html
- ott_posts/views.py
- taxi_posts/templates/taxi_posts/base.html
- taxi_posts/templates/taxi_posts/navbar.html
- taxi_posts/templates/taxi_posts/ride_list.html
- taxi_posts/views.py
contest 앱 생성, 페이지네이션 수정
어떤 변경 사항이 있나요?
> Feat: contest 앱 생성, 페이지네이션 수정

- contest/static/contest/css/list.css
- contest/templates/contest/contest_list.html
- contest/urls.py
- contest/views.py
- ott_posts/views.py
- taxi_posts/templates/taxi_posts/footer.html
- taxi_posts/views.py
- www/settings.py
> Feat: 반응형으로 변경

- contest/forms.py
- contest/models.py
- contest/templates/contest/contest_detail.html
- contest/templates/contest/contest_list.html
- contest/views.py
- www/urls.py
> Feat:댓글 생성

- prj_posts/admin.py
- prj_posts/forms.py
- prj_posts/models.py
- prj_posts/templates/prj_posts/base.html
- prj_posts/templates/prj_posts/prj_detail.html
- prj_posts/templates/prj_posts/prj_edit.html
- prj_posts/templates/prj_posts/prj_form.html
- prj_posts/templates/prj_posts/prj_list.html
- prj_posts/urls.py
- prj_posts/views.py
- study_posts/admin.py
- study_posts/forms.py
- study_posts/models.py
- study_posts/templates/study_posts/base.html
- study_posts/templates/study_posts/study_detail.html
- study_posts/templates/study_posts/study_edit.html
- study_posts/templates/study_posts/study_form.html
- study_posts/templates/study_posts/study_list.html
- study_posts/urls.py
- study_posts/views.py
> Feat:prj_posts, study_posts 생성

- contest/models.py
- contest/templates/contest/contest_detail.html
- www/urls.py
> Feat: url 수정

- prj_posts/templates/prj_posts/prj_form.html
- study_posts/templates/study_posts/study_form.html
- study_posts/templates/study_posts/study_update.html
> study_update 파일 생성, prj&study의 form 제목 변경

- ott_posts/forms.py
- prj_posts/templates/prj_posts/prj_detail.html
- prj_posts/views.py
- study_posts/templates/study_posts/study_detail.html
- taxi_posts/forms.py
- taxi_posts/templates/taxi_posts/navbar.html
- www/urls.py
ott,taxi forms.py 수정
어떤 변경 사항이 있나요?
> Feat: ott,taxi forms.py 수정

- prj_posts/templates/prj_posts/prj_list.html
- prj_posts/urls.py
- prj_posts/views.py
- study_posts/templates/study_posts/study_list.html
- study_posts/views.py
> prj, study 수정

- users/static/users/css/login.css
- users/templates/users/login.html
Feat: 로그인 html 생성
어떤 변경 사항이 있나요?
> Feat: 로그인 html 생성

- users/static/users/css/signup.css
- users/templates/users/signup.html
> Feat: 회원가입  html 생성

- contest/templates/contest/contest_list.html
- prj_posts/templates/prj_posts/prj_detail.html
- prj_posts/templates/prj_posts/prj_list.html
- taxi_posts/static/taxi_posts/css/list.css
- taxi_posts/templates/taxi_posts/base.html
- taxi_posts/templates/taxi_posts/navbar.html
- users/forms.py
- users/models.py
- users/templates/users/login.html
- users/templates/users/signup.html
- users/urls.py
- users/views.py
- www/urls.py
로그인, 회원가입 기능 추가
회원가입 - ID, 전화번호, 비밀번호 입력
로그인 - ID, 비밀번호 입력
어떤 변경 사항이 있나요?
> Feat: 로그인 기능 추가

- taxi_posts/templates/taxi_posts/navbar.html
- users/forms.py
- users/models.py
- users/templates/users/signup.html
- users/urls.py
- users/views.py
> Feat:로그아웃 기능 생성

- contest/models.py
- contest/templates/contest/contest_detail.html
- contest/templates/contest/contest_list.html
- users/views.py
> Fix: 로그인 수정

- users/templates/users/main_page.html
> Feat: 메인페이지 생성

- contest/static/contest/css/detail.css
- contest/templates/contest/contest_detail.html
- users/templates/users/main_page.html
- users/views.py
> Feat: 메인페이지 백 연결

- contest/models.py
- contest/static/contest/css/detail.css
- contest/templates/contest/contest_detail.html
- contest/urls.py
- contest/views.py
- taxi_posts/templates/taxi_posts/base.html
- taxi_posts/templates/taxi_posts/navbar.html
- users/templates/users/mypage.html
- users/urls.py
- users/views.py
공모전 스크랩 하면 마이페이지에 뜨게 함 
어떤 변경 사항이 있나요?
공모전 스크랩하면 마이페이지에 스크랩한 공모전 뜨는데 아직 css는 미완성,,,,,,,
일단 다른 기능 먼저 구현 할게요,,ㅎ
> Feat: 스크랩 기능 생성

- contest/static/contest/css/detail.css
- contest/static/contest/css/list.css
- contest/templates/contest/contest_detail.html
- contest/templates/contest/contest_list.html
- contest/views.py
- ott_posts/models.py
- users/templates/users/mypage.html
- users/views.py
> Feat: D-Day 기능 생성

- contest/templates/contest/contest_list.html
- contest/views.py
- ott_posts/forms.py
- ott_posts/models.py
- ott_posts/templates/ott_posts/ott_detail.html
- ott_posts/views.py
- users/templates/users/signup.html
자신이 쓴 글만 수정/삭제 가능하게 구현, 로그인한 사용자만 글 작성 가능하게 구현
어떤 변경 사항이 있나요?
> Feat: 자신이 쓴 글만 수정/삭제 가능하게

- taxi_posts/forms.py
- taxi_posts/models.py
- taxi_posts/templates/taxi_posts/ride_detail.html
- taxi_posts/views.py
글 작성한  사람만 글 수정/삭제 가능하게
어떤 변경 사항이 있나요?
> Feat: 글 작성한  사람만 글 수정/삭제 가능하게

- ott_posts/views.py
- prj_posts/forms.py
- prj_posts/models.py
- prj_posts/templates/prj_posts/prj_detail.html
- prj_posts/views.py
- study_posts/forms.py
- study_posts/models.py
- study_posts/templates/study_posts/study_detail.html
- study_posts/views.py
- taxi_posts/views.py
prj,study 앱에서 자신이 쓴 글만 삭제/수정 가능하게 변경,
로그인한 사용자만 글 작성 가능하게 구현
어떤 변경 사항이 있나요?
> Feat: 자신이 쓴 글만 삭제, 수정 가능하게 변경

- contest/static/contest/css/list.css
- contest/templates/contest/contest_list.html
css 수정
어떤 변경 사항이 있나요?
- [ｘ] CSS 등 사용자 UI 디자인 변경
> Feat: css 수정

- users/models.py
- users/templates/users/mypage.html
- users/urls.py
- users/views.py
본인이 작성한 글 조회 기능 추가
본인이 작성한 글 조회 기능 추가
어떤 변경 사항이 있나요?
> 본인이 작성한 글 조회 기능 추가

- chat/admin.py
- chat/apps.py
- chat/models.py
- chat/static/chat/css/chat.css
- chat/templates/chat/chat_room.html
- chat/tests.py
- chat/urls.py
- chat/views.py
- contest/static/contest/css/list.css
- contest/templates/contest/contest_list.html
- ott_posts/templates/ott_posts/ott_detail.html
- ott_posts/templates/ott_posts/ott_list.html
- ott_posts/views.py
- prj_posts/templates/prj_posts/prj_list.html
- study_posts/templates/study_posts/study_list.html
- taxi_posts/templates/taxi_posts/ride_list.html
- users/templates/users/mypage.html
- users/urls.py
- users/views.py
- www/settings.py
- www/urls.py
마이페이지 내가 쓴글 볼 수 있게,게시판 검색창 생성, chat앱 생성
어떤 변경 사항이 있나요?
> Feat: 마이페이지 내가 쓴글 볼 수 있게,게시판 검색창 생성, chat앱 생성

- contest/static/contest/css/detail.css
- contest/templates/contest/comment.html
- contest/templates/contest/contest_detail.html
- contest/templates/contest/contest_list.html
- contest/templates/contest/contest_search.html
- contest/views.py
- ott_posts/templates/ott_posts/ott_list.html
- ott_posts/templates/ott_posts/ott_search.html
- prj_posts/templates/prj_posts/prj_list.html
- prj_posts/templates/prj_posts/prj_search.html
- study_posts/templates/study_posts/study_list.html
- study_posts/templates/study_posts/study_search.html
- taxi_posts/templates/taxi_posts/ride_list.html
- taxi_posts/templates/taxi_posts/ride_search.html
- users/templates/users/login.html
- users/views.py
> Feat: 찜 버튼 추가

- taxi_posts/templates/taxi_posts/map.html
- taxi_posts/templates/taxi_posts/ride_form.html
- taxi_posts/templates/taxi_posts/ride_list.html
- taxi_posts/views.py
카풀 게시판에서 지도에서 장소 선택하면 목적지에 입력되게 구현
어떤 변경 사항이 있나요?
> Feat: 카풀게시판에서 지도에서 장소 선택하면 목적지에 입력되게 구현

- taxi_posts/templates/taxi_posts/map.html
- taxi_posts/templates/taxi_posts/ride_form.html
- taxi_posts/urls.py
- taxi_posts/views.py
> Feat: 지도 생성

- README.md
- contest/forms.py
- contest/models.py
- contest/static/contest/css/detail.css
- contest/templates/contest/comment.html
- contest/templates/contest/contest_detail.html
- contest/templates/contest/contest_list.html
- contest/views.py
> Feat: 댓글 수정 기능

- users/templates/users/main_page.html
Feat: 메인페이지 슬라이드 완성
메인페이지 카테고리 설명 슬라이드 완성, users/static/images 이미지 5개 추가
어떤 변경 사항이 있나요?
> Feat: 메인페이지 슬라이드 완성

- ott_posts/templates/ott_posts/ott_detail.html
- ott_posts/templates/ott_posts/ott_list.html
- prj_posts/templates/prj_posts/prj_detail.html
- prj_posts/templates/prj_posts/prj_list.html
- study_posts/templates/study_posts/study_detail.html
- study_posts/templates/study_posts/study_list.html
- taxi_posts/templates/taxi_posts/ride_detail.html
- taxi_posts/templates/taxi_posts/ride_list.html
> 디테일 페이지 수정, 삭제 버튼 수정

- README.md
- chat/static/chat/css/chat.css
- chat/templates/chat/chat_room.html
- chat/views.py
- ott_posts/templates/ott_posts/ott_form.html
- prj_posts/forms.py
- prj_posts/templates/prj_posts/prj_update.html
- study_posts/forms.py
- study_posts/templates/study_posts/study_form.html
- taxi_posts/templates/taxi_posts/map.html
- taxi_posts/templates/taxi_posts/map2.html
- taxi_posts/templates/taxi_posts/ride_form.html
- users/static/users/css/mainpage.css
- users/templates/users/main_page.html
> Feat: 전체적인 css  수정

- contest/static/contest/css/detail.css
- contest/templates/contest/comment.html
- contest/templates/contest/contest_search.html
- contest/views.py
- ott_posts/templates/ott_posts/ott_detail.html
- ott_posts/templates/ott_posts/ott_list.html
- ott_posts/templates/ott_posts/ott_update.html
- prj_posts/templates/prj_posts/prj_detail.html
- prj_posts/templates/prj_posts/prj_list.html
- prj_posts/templates/prj_posts/prj_update.html
- study_posts/templates/study_posts/study_detail.html
- study_posts/templates/study_posts/study_list.html
- study_posts/templates/study_posts/study_update.html
- taxi_posts/static/taxi_posts/css/list.css
- taxi_posts/templates/taxi_posts/base.html
- taxi_posts/templates/taxi_posts/footer.html
- taxi_posts/templates/taxi_posts/ride_detail.html
- taxi_posts/templates/taxi_posts/ride_list.html
- taxi_posts/templates/taxi_posts/ride_update.html
- users/static/users/css/login.css
- users/templates/users/login.html
- users/templates/users/main_page.html
> Feat: 버그 수정

- ott_posts/templates/ott_posts/ott_detail.html
- ott_posts/templates/ott_posts/ott_list.html
- prj_posts/templates/prj_posts/prj_detail.html
- prj_posts/templates/prj_posts/prj_list.html
- study_posts/templates/study_posts/study_detail.html
- study_posts/templates/study_posts/study_list.html
- taxi_posts/templates/taxi_posts/ride_detail.html
- taxi_posts/templates/taxi_posts/ride_list.html
> Fix: 버그 수정

- users/forms.py
- users/templates/users/signup.html
회원가입할 때 전화번호 형식 다르면 안되게 설정
-> 010-XXXX-XXXX 이런식으로 입력해야 회원가입 가능하게 설정
어떤 변경 사항이 있나요?
> Feat: 회원가입할 때 전화번호 형식 다르면 안되게 설정

- chat/static/chat/css/chat.css
- chat/templates/chat/chat_room.html
- chat/views.py
- www/settings.py
채팅방 날짜 추가, 방화벽 설정
어떤 변경 사항이 있나요?
> Feat: 채팅방 날짜 추가, 방화벽 설정

- chat/templates/chat/chat_room.html
- chat/views.py
- contest/templates/contest/comment.html
- contest/templates/contest/contest_detail.html
- contest/templates/contest/contest_list.html
- prj_posts/forms.py
- taxi_posts/templates/taxi_posts/navbar.html
> Fix: 스크랩 버그 수정

- ott_posts/forms.py
- ott_posts/templates/ott_posts/ott_detail.html
- ott_posts/templates/ott_posts/ott_form.html
- taxi_posts/templates/taxi_posts/map.html
- taxi_posts/templates/taxi_posts/map2.html
- taxi_posts/templates/taxi_posts/ride_form.html
- users/forms.py
- users/templates/users/edit.html
> Feat: 예상택시비 기능 추가

- contest/templates/contest/contest_detail.html
- contest/templates/contest/contest_list.html
- taxi_posts/templates/taxi_posts/navbar.html
> Fix: D-DAY 수정
